version: "3.3"
services:
# The priority used by Compose to choose which env var value to use:
# 1. Compose file
# 2. Shell environment variables
# 3. Environment file
# 4. Dockerfile
# 5. Variable is not defined

  # CB-Spider
  cb-spider:
    image: cloudbaristaorg/cb-spider:0.8.10
    container_name: mc-infra-connector #cb-spider
    ports:
      - "0.0.0.0:1024:1024"
      - "0.0.0.0:2048:2048"
      - "0.0.0.0:4096:4096"
    volumes:
      - ./conf/cb-spider/:/root/go/src/github.com/mcc/cb-spider/conf/
      - ./data/cb-spider/meta_db/:/root/go/src/github.com/mcc/cb-spider/meta_db/
      - ./data/cb-spider/log/:/root/go/src/github.com/mcc/cb-spider/log/
    #depends_on:
      #- cb-restapigw
    environment:
      - PLUGIN_SW=OFF
      # if you leave these values empty, REST Auth will be disabled.
      - API_USERNAME=
      - API_PASSWORD=


  # CB-Tumblebug
  cb-tumblebug:
    image: cloudbaristaorg/cb-tumblebug:0.8.4
    container_name: mc-infra-manager #cb-tumblebug
    ports:
      - "0.0.0.0:1323:1323"
      - "0.0.0.0:50252:50252"
    depends_on:
      #- cb-restapigw
      - cb-spider
      # - cb-tumblebug-mysql
    volumes:
      - ./conf/cb-tumblebug/:/app/conf/
      - ./data/cb-tumblebug/meta_db/:/app/meta_db/
      - ./data/cb-tumblebug/log/:/app/log/
    environment:
      - SPIDER_CALL_METHOD=REST
      - SPIDER_REST_URL=http://cb-spider:1024/spider
      - DRAGONFLY_REST_URL=http://cb-dragonfly:9090/dragonfly
      - API_USERNAME=default
      - API_PASSWORD=default
      - CB_NETWORK_SERVICE_ENDPOINT=localhost:8053
      - CB_NETWORK_ETCD_ENDPOINTS="localhost:2379"
      - AUTOCONTROL_DURATION_MS=10000
      - SELF_ENDPOINT=localhost:1323
      - GOLANG_PROTOBUF_REGISTRATION_CONFLICT=ignore
      - API_DOC_PATH=/app/src/api/rest/docs/swagger.json
      # - DB_URL=cb-tumblebug-mysql:3306
      # - DB_DATABASE=cb_tumblebug
      # - DB_USER=cb_tumblebug
      # - DB_PASSWORD=cb_tumblebug
      # - GODEBUG=netdns=go